// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/crispyfishtech/crispyfish-demo/views/components"

func Index(
	title string,
	showVersion bool,
	metadata string,
	refreshInterval int,
	expireInterval int,
	removeInterval int,
	skipErrors bool,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header(title).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body class=\"bg-gray-500 min-h-screen flex flex-col items-center justify-center\"><div class=\"w-full mx-auto p-8 h-screen flex items-center\"><div class=\"flex flex-col gap-8 md:flex-row w-full h-full\"><!-- Left Column --><div class=\"md:w-2/6 flex flex-col items-center bg-gray-900 rounded-xl shadow-lg p-8 h-full\"><div class=\"mb-4 text-gray-400 text-sm\">Inspired by <a href=\"https://github.com/oskapt/rancher-demo\" target=\"_blank\" class=\"underline hover:text-cyan-400\">oskapt/rancher-demo</a></div><img class=\"w-40 h-40 mb-6\" src=\"/static/img/cft-light.png\" alt=\"Crispyfish Logo\"><div class=\"mb-6 flex flex-col items-center\"><div class=\"text-5xl font-bold text-cyan-400\" id=\"container-count\"></div><div class=\"text-lg text-gray-300\" id=\"container-count-label\"></div></div><div class=\"mb-4 flex flex-col items-center container-backend hidden\" id=\"container-backend\"><div class=\"text-2xl font-semibold text-white\" id=\"current-container\"></div><div class=\"text-gray-400 text-sm\">current backend</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if showVersion {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"mb-4 flex flex-col items-center container-backend hidden\"><div class=\"text-xl font-semibold text-white\" id=\"current-container-version\"></div><div class=\"text-gray-400 text-sm\">current version</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"mb-4 flex flex-row gap-6 items-center\"><div class=\"flex flex-col items-center\"><div class=\"text-lg text-cyan-400\" id=\"requests-count\"></div><div class=\"text-xs text-gray-400\">requests</div></div><div class=\"flex flex-col items-center\"><div class=\"text-lg text-red-500\" id=\"requests-error-count\">0</div><div class=\"text-xs text-gray-400\">errors</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if metadata != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"mt-4 text-gray-400 text-center\" id=\"extra-info\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(metadata)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/index.templ`, Line: 51, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><!-- Right Column --><div class=\"md:w-4/6 h-full flex\"><div class=\"bg-gray-900 rounded-xl shadow-lg p-8 w-full h-full flex flex-col\"><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 container-group flex-1\"><!-- Cards will be dynamically inserted here --></div></div></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
